"""Example 08 — fusion-code integration skeleton (ARCH-3).

Demonstrates how an upstream agent (fusion-code) should delegate command
execution to fusion-executor instead of running its own subprocess + file IO.
This file lives in fusion-executor and consumes the executor API only — it does
NOT import fusion-code. It is a one-way reference skeleton for the integration
described in the fusion-code issue "Refactor: delegate command execution to
fusion-executor (ExecutorDriver interface)".

The self-healing loop shows the two contract points fusion-code must own:

1. Diagnostics parsing — on exit_code != 0, read `result.diagnostics`
   (error_type / file_path / line_number / code_snippet) to build the next
   model prompt. The executor already sliced the traceback; fusion-code must
   not re-parse raw stdout.
2. Circuit breaker — the executor is per-task stateless by design, so it does
   NOT count consecutive failures. The caller owns that count and reads
   `RollbackPolicy.max_consecutive_failures` as the threshold. Hitting it stops
   the loop (fail visibly) instead of looping forever.

Auto-rollback (optional, FR-04): pass `auto_rollback=RollbackPolicy(...)` to
`run()` and the executor rolls the git snapshot back on failure + detected file
damage, setting `result.auto_rolled_back=True`. The caller still owns the
consecutive-failure count — auto-rollback is per-execute, not per-loop.

    python examples/08_integrate_fusion_code.py
"""

from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path

from fusion_executor import (
    ExecutionResult,
    FusionSandboxExecutor,
    RollbackPolicy,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("integrate")


def git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, check=True)


def heal_one(ex: FusionSandboxExecutor, repo: Path, attempt: int) -> ExecutionResult:
    # In fusion-code this command is generated by the model from the prior
    # diagnostics. Here we just run a known-good fix so the loop converges.
    # First pass: a command that fails (broken import) -> diagnostics flow.
    # Second pass: a command that passes -> loop exits.
    cmd = "python3 -c 'import nonexistent_pkg'" if attempt == 0 else "python3 -c 'print(42)'"
    result = ex.run(
        cmd,
        cwd=str(repo),
        task_id=f"heal-{attempt}",
        timeout_sec=10.0,
        auto_rollback=RollbackPolicy(max_consecutive_failures=3, file_damage_check=True),
    )
    return result


def self_heal_loop(ex: FusionSandboxExecutor, repo: Path, max_failures: int) -> bool:
    consecutive_failures = 0
    attempt = 0
    while attempt < 10:
        result = heal_one(ex, repo, attempt)
        logger.info(
            "attempt=%d exit=%d auto_rolled_back=%s trace_id=%s",
            attempt,
            result.exit_code,
            result.auto_rolled_back,
            result.trace_id,
        )
        if result.exit_code == 0:
            return True
        consecutive_failures += 1
        # Parse the sliced diagnostics — this is what feeds the next model turn.
        if result.diagnostics:
            logger.warning(
                "diagnostics: %s @ %s:%s",
                result.diagnostics.error_type,
                result.diagnostics.file_path,
                result.diagnostics.line_number,
            )
        # Circuit breaker: executor is stateless, caller owns this count.
        if consecutive_failures >= max_failures:
            logger.error("circuit breaker tripped after %d consecutive failures", consecutive_failures)
            return False
        attempt += 1
    return False


def main() -> None:
    ex = FusionSandboxExecutor()
    with tempfile.TemporaryDirectory(prefix="fe-integrate-") as td:
        repo = Path(td)
        git(repo, "init", "-q")
        git(repo, "config", "user.email", "demo@fusion.local")
        git(repo, "config", "user.name", "demo")
        (repo / "app.py").write_text("print('hello')\n")
        git(repo, "add", "-A")
        git(repo, "commit", "-q", "-m", "init")

        # max_consecutive_failures is the caller-side threshold (ARCH-7).
        ok = self_heal_loop(ex, repo, max_failures=3)
        print(f"self-heal loop ok={ok}")
        if not ok:
            raise SystemExit("self-heal loop did not converge")


if __name__ == "__main__":
    main()
